
const OK = 200

const CREATED = 201

const BAD_REQUEST = 400

const NOT_FOUND = 404

const UNAUTHORIZED = 401

const FORBIDDEN = 403

module.exports = {OK, CREATED, BAD_REQUEST, NOT_FOUND, UNAUTHORIZED, FORBIDDEN}